[package]
description = "CosmWasm integration testing for Merlin"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "merlin-test-tube"
repository = "https://github.com/merlins-labs/test-tube"
version = "16.0.1"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = ["merlin", "test_artifacts"]

[dependencies]
base64 = "0.13.0"
cosmrs = {version = "0.9.0", features = ["cosmwasm"]}
cosmwasm-std = "1.1.2"
merlin-std = "0.16.0"
prost = "0.11.0"
serde = "1.0.144"
serde_json = "1.0.85"
test-tube = {version = "0.1.5", path = "../test-tube"}
thiserror = "1.0.34"

[build-dependencies]
bindgen = "0.60.1"

[dev-dependencies]
cw1-whitelist = "0.15.0"
rayon = "1.5.3"
